/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 ./public/A1-A4/A1.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useLoader } from '@react-three/fiber';
import { GLTFLoader } from 'three/examples/jsm/Addons.js';

export function DragonFLy() {

  const gltf = useLoader(GLTFLoader, '/lights/dragonFly.glb');

  return (
    <>
      <primitive object={gltf.scene} position={[0.0, 0.035, 0.061]} rotation={[ 0,0, 0]}/>
    </>
  
  )
}

useGLTF.preload('/lights/dragonFly.glb')
