/*
auto-generated by: https://github.com/pmdrs/gltfjsx
author: abcdef (https://sketchfab.com/abcdef)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/...
title: Model
*/
import { Canvas } from '@react-three/fiber'
import fileD from './GalaxyS10.gltf'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Model(props) {

    
    const { nodes, materials } = useGLTF(fileD)

    console.log(nodes)
    console.log(materials)

  return (
    <Canvas>

    <group>
        <mesh geometry={nodes.object_4} material={materials["Scene_-_Root"]}/>
    </group>
    </Canvas>
  )
}

useGLTF.preload(fileD)