import ProfessionLayout from "../professionLayout";


export default function DentalPage() {
    return(
    <ProfessionLayout>

        <section id="module1" class="section section--grey-extra-light-dusted">
    <div class="grid-wrap grid-wrap--small">
        <header class="section__header">
            <h2>Customised dental loupes</h2>
        </header>
        <div class="rich-text">
            <p><span>The most frequent reason for dentists </span><span>and other dental professionals </span><span>leaving their job prematurely is pain and injury caused by bad working environment.&nbsp;</span><span>Fortunately, i</span><span>t does not have to be that way.&nbsp;</span><span>The solution is optical.</span>&nbsp;</p>
            <p><span>Dental</span><span>&nbsp;</span><span>examinations and procedures</span><span> require precision, and your eyes are your primary instrument. </span><span>Therefore</span><span>, </span><span>many dentist</span><span>s</span><span> and dental specialists</span><span>&nbsp;tend to&nbsp;</span><span>crouch&nbsp;</span><span>over the patient&nbsp;</span><span>to be close enough to see</span><span>&nbsp;</span><span>their</span><span>&nbsp;work</span><span>. With</span><span>&nbsp;m</span><span>a</span><span>gni</span><span>fying dental loupes</span><span>, you are able to&nbsp;</span><span>see</span><span>&nbsp;your precision work</span><span>&nbsp;from a good and upright working position.</span><span> A position that spares your body and secures a better, ergonomic, working posture</span><span>.</span>&nbsp;</p>
            <p><span>All</span><span> </span><span>dental loupes from </span><span>ExamVision</span><span>&nbsp;are&nbsp;</span><span>designed by optometrists</span><span>&nbsp;and&nbsp;</span><span>customised</span><span> to the individual dentist,</span><span> oral surgeon and other dental specialists</span><span>. Each solution is based on individual eyesight,</span><span>&nbsp;</span><span>need for magnification as well as physical working environment such as distance and tools and facilities available in the dental clinic.</span>&nbsp;</p>
            <p><strong><span>Improve your working environment with dental loupes</span></strong>&nbsp;<br/><span>One of the main benefits of working with dental magnifying glasses</span><span>&nbsp;designed for&nbsp;</span><span>dentists and&nbsp;</span><span>dental specialists </span><span>is an immediate improvement in working posture.</span><span>&nbsp;</span><span>Without dental loupes,</span><span>&nbsp;dentists and</span><span>&nbsp;</span><span>dental professionals</span><span>&nbsp;tend to work in&nbsp;</span><span>crouched</span><span>, uncomfortable po</span><span>s</span><span>itions that lead to chronic pains in</span><span>&nbsp;the neck and</span><span>&nbsp;lower</span><span>&nbsp;part of</span><span>&nbsp;back.</span>&nbsp;</p>
            <p><span>By including dentistry loupes for dental procedures in your toolbox, your working environment will improve </span><span>significantly </span><span>– in the short as well as in the long term.</span>&nbsp;</p>
            <p><strong><span>C</span></strong><strong><span>ustomised dental magnification loupes</span></strong><strong><span>&nbsp;for individual needs</span></strong>&nbsp;<br/><span>Our team of&nbsp;</span><span>optometrists and highly trained specialists&nbsp;</span><span>can help you&nbsp;</span><span>get</span><span> the right level of magnification</span><span> for your dental loupes</span><span>.</span><span> Based on your requirements and our expertise, we will guide </span><span>you&nbsp;</span><span>and customise the best dental loupe solution for you – a solution that is uniquely fitted for your eyes </span><span>while</span><span>&nbsp;facilitating a superior ergonomic position.</span>&nbsp;</p>
            <p><span>To support you and your working day in the best possible way, we offer Monofocal carrier lenses, as well as Multifocal carrier lenses (also known as varifocal or progressive lenses). It is also possible to customise the lenses in the dental loupe oculars to match your prescription. <a rel="noopener" href="/loupes-lights/optics-safety/" target="_blank" title="Optics &amp; safety">L</a></span><a rel="noopener" href="/loupes-lights/optics-safety/" target="_blank" title="Optics &amp; safety"><span>earn more about our optical solutions</span></a><span>.&nbsp;</span>&nbsp;</p>
            <p><span>No matter the prescription, we&nbsp;</span><span>only</span><span>&nbsp;use</span><span>&nbsp;the best lenses and optics available. This include coatings&nbsp;</span><span>to&nbsp;</span><span>protect against harmful UV-light,</span><span>&nbsp;to</span><span>&nbsp;reduc</span><span>e</span><span>&nbsp;refle</span><span>ct</span><span>ions and mak</span><span>e</span><span>&nbsp;the lenses resistant to scratches and smudges.&nbsp;</span><span>You can s</span><span>ee&nbsp;</span><span>more about the measurements taken to&nbsp;</span><span>protect your eyes&nbsp;</span><a rel="noopener" href="/loupes-lights/optics-safety/#module6" target="_blank" title="Optics &amp; safety" data-anchor="#module6"><span>here</span></a><span>.</span>&nbsp;</p>
        </div>

            <button class="btn btn--readmore" data-action="readmore">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><rect width="16" height="2" rx="1" transform="rotate(90 4.5 4.5)" fill="#fff"></rect><rect width="16" height="2" rx="1" transform="translate(0 7)" fill="#fff"></rect></svg>
                <span>Read more</span>
            </button>
            <div class="rich-text read-more" style={{height:"0px"}}>
                <div class="read-more__wrap">
                    <p><strong><span>Dental loupe magnification for dental precision</span></strong>&nbsp;<br/><span>A crucial prerequisite for performing&nbsp;</span><span>modern dental procedure and operation techniques&nbsp;</span><span>is vision. Of course, eyesight and age are important elements in this</span><span>&nbsp;– but h</span><span>aving the right optical solution, using prescription in both carrier lenses and loupe oculars is vital in order to have a clear vision.</span>&nbsp;</p>
                    <p><span>Having the&nbsp;</span><span>proper level of</span><span>&nbsp;magnification&nbsp;</span><span>will&nbsp;</span><span>help you perform better&nbsp;</span><span>in</span><span>&nbsp;all dental&nbsp;</span><span>examinations and&nbsp;</span><span>procedures whether you're a dentist, oral surgeon, orthodontist or other dental specialist. </span><span>Therefore, we will always examine your vision and physical working environment before designing your dental loupes. However, i</span><span>n general we recommend th</span><span>e</span><span>se</span><span>&nbsp;magnifications</span><span>&nbsp;for dent</span><span>al precision</span><span>:</span>&nbsp;</p>
                    <ul>
                    <li data-leveltext="-" data-font="Calibri" data-listid="2" aria-setsize="-1" data-aria-posinset="1" data-aria-level="1"><span>Lower loupe magnifications from 2.3x to 3.3x are often sufficient for general dentistry, diagnostics, extractions, implants, orthodontics etc. Hygienists working with dental hygiene procedures or dental students rarely need magnifications above 3.3x in their loupes. </span><span>This is partly&nbsp;</span><span>due to the fact, that most of&nbsp;</span><span>these</span><span>&nbsp;are&nbsp;</span><span>under</span><span>&nbsp;the age of 40.</span><span>&nbsp;</span>&nbsp;</li>
                    <li data-leveltext="-" data-font="Calibri" data-listid="2" aria-setsize="-1" data-aria-posinset="2" data-aria-level="1"><span>Higher loupe magnifications from 3.5x to 6.4x are often suited for precision crown and bridge, composites and aesthetics, periodontal surgery, final margin verifications, complicated endodontics such as accessory canals, complicated diagnostics including horizontal and vertical fractures and similar procedures. </span>&nbsp;</li>
                    </ul>
                    <p><span>All in all, we offer a range of 14 magnifications within five dental loupe systems. <a rel="noopener" href="/loupes-lights/magnifications/" target="_blank" title="Magnifications">S</a></span><a rel="noopener" href="/loupes-lights/magnifications/" target="_blank" title="Magnifications"><span>ee our wide range of magnifications</span><span> here</span><span></span><span>.</span>&nbsp;</a></p>
                    <p><strong>Ergonomic guidance for dentists and other dental specialists working with loupes<br/></strong><span>Part of our service</span><span>, when you order a dental loupe solution with us,</span><span> is an examination of your ergonomic working environment. </span><span>Our team of experts&nbsp;</span><span>will</span><span>&nbsp;guide you in all aspects&nbsp;</span><span>of ergonomics</span><span> to optimise your</span><span>&nbsp;physical working environment</span><span> for you and your colleagues while finding the best loupe solution for you, whether you work as a dentist, oral surgeon, orthodontist or other dental specialist</span><span>.&nbsp;</span><span>Among other elements, our focus is on your working position</span><span>&nbsp;and working distance</span><span>&nbsp;with the proper</span><span>&nbsp;adjustment</span><span>&nbsp;of your dental chair</span><span>&nbsp;– to support your neck and back – but also your eyesight. We also look into the possibilities to</span><span>&nbsp;place tools and equipment</span><span>&nbsp;smarter</span><span>, sufficient and good lightning</span><span>&nbsp;as well as examine the options for&nbsp;</span><span>protection of your eyesight from harmful UV and blue-violet light.&nbsp;</span><span>Further, we will also look into&nbsp;</span><span>optimis</span><span>ing</span><span>&nbsp;your working position by placing your patients</span><span>&nbsp;in a different way.</span>&nbsp;</p>
                    <p><span>Prolonged periods</span><span>&nbsp;of working</span><span>&nbsp;in static postures&nbsp;</span><span>will&nbsp;</span><span>cause significant&nbsp;</span><span>pains and injuries. Therefore</span><span>,&nbsp;</span><span>our team of experts will</span><span>&nbsp;also</span><span>&nbsp;</span><span>give</span><span>&nbsp;you and your colleagues&nbsp;</span><span>advice and guidance on how to change</span><span>&nbsp;your working positions</span><span>&nbsp;on a regular basis and provide you with&nbsp;</span><span>stretching exercises</span><span>.</span>&nbsp;</p>
                    <p><span>Not only will&nbsp;</span><span>this focus on work-life ergonomics</span><span> help you achieve better treatment results, faster procedures, happy well-treated patients – it will also ensure a safe and sound working environment </span><span>and&nbsp;</span><span>improve your</span><span>&nbsp;</span><span>work</span><span>&nbsp;</span><span>satisfaction</span><span>&nbsp;– and you will feel the difference in the short as well as in the long term.</span>&nbsp;</p>
                    <p><strong><span>Age affects your eyesight</span></strong>&nbsp;<br/><span>People under 40 years of age very often have close to perfect eyesight</span><span>, and the&nbsp;</span><span>eye</span><span>s</span><span>&nbsp;</span><span>are</span><span>&nbsp;able to adjust to changes quite quickly</span><span>. Th</span><span>erefore, people within this age-range will</span><span>&nbsp;have a large depth of field and&nbsp;</span><span>will&nbsp;</span><span>rarely need dental </span><span>loupes with more than&nbsp;</span><span>3.0x</span><span>&nbsp;magnification</span><span>. If the eyesight is</span><span>&nbsp;not</span><span> flawless, both carriers and oculars can be customised with the right prescriptions in order to compensate.</span>&nbsp;</p>
                    <p><span>Turning 40,&nbsp;</span><span>the&nbsp;</span><span>eyesight will&nbsp;</span><span>gradually be weakened. To be able to perform dental examinations and procedures, you will need an optical loupe solution to compensate and continue to work with precision. Our </span><span>magnifying</span><span>&nbsp;loupes</span><span>&nbsp;will enforce your actual eyesight</span><span>&nbsp;but can also&nbsp;</span><span>be altered to continuous changes in your eyesight.</span> This is very important when choosing the best dental loupe solution for a long career as a dentist or other specialist in dentistry.</p>
                    <p><span>No matter your age and prescription, a</span><span>ll our&nbsp;</span><span>dental loupes</span><span>&nbsp;are&nbsp;</span><span>designed by optometrists,&nbsp;</span><span>produced</span><span>&nbsp;in Denmark and fitted&nbsp;</span><span>to individual needs and&nbsp;</span><span>practices&nbsp;</span><span>by</span><span>&nbsp;local</span><span>&nbsp;optical professionals</span><span>&nbsp;across the world</span><span>.</span>&nbsp;</p>
                </div>
            </div>
    </div>
</section>
        
    </ProfessionLayout>
    )
}